# render.yaml
services:
  - type: web
    name: dialect-translator-api
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python api.py"
    branch: master
    autoDeploy: true
